### GET request to example server
GET http://localhost:3000/tiles/style/pbb-nop/11/1631/1060

### GET request to example server
GET http://localhost:3000/tiles/style/pbb-nop/11/1631/1060?filter=[{"layerId":"pbb","filter":["all",["==",["slice",["get", "NOP"],0,4],"3172"]]}]


### GET request to example server
GET http://localhost:3000/styles/bidang-pbb/11/1631/1060

### GET request to example server
GET http://localhost:3000/styles/bidang-pbb/11/1631/1060

### GET request to example server
GET http://localhost:3000/styles/bidang-pbb/11/1631/1060
### GET request to example server
GET http://localhost:3000/styles/bidang-pbb/11/1631/1060
###

GET http://localhost:8080/styles/bidang-nop/11/1631/988.png

###
GET http://localhost:8080/styles/bidang-nop/512/11/1631/1060.png
